export const article: string;
export const device: string;
export const introduction: string;
export const interface: string;
export const architecture: string;
export const imageStack: string;
export const imageHolder: string;
export const row: string;
export const logos: string;
